In [44]:
import pandas as pd
import numpy as np

from tqdm.notebook import tqdm

In [2]:
db = pd.read_parquet(
    "/home/sergey/projects/Credit_scoring/raw/train_data/train_data_0.pq", 
    engine="pyarrow"
)

In [10]:
db[:20].columns

61

In [3]:
db.describe().iloc[1:, 1:]

rn  pre_since_opened  pre_since_confirmed  pre_pterm  pre_fterm  \
mean   6.537471          9.271325             8.330264   8.299071   8.309444   
std    5.121167          5.773757             4.593511   5.245598   4.464844   
min    1.000000          0.000000             0.000000   0.000000   0.000000   
25%    3.000000          4.000000             5.000000   4.000000   6.000000   
50%    5.000000          9.000000             9.000000   8.000000   8.000000   
75%    9.000000         14.000000            11.000000  13.000000  12.000000   
max   51.000000         19.000000            17.000000  17.000000  16.000000   

      pre_till_pclose  pre_till_fclose  pre_loans_credit_limit  \
mean         6.991781         8.337011                9.740888   
std          5.184165         4.233992                5.799625   
min          0.000000         0.000000                0.000000   
25%          1.000000         5.000000                5.000000   
50%          6.000000        10.000000               10.000000   
75%         12.000000        11.000000               15.000000   
max         16.000000        15.000000               19.000000   

      pre_loans_next_pay_summ  pre_loans_outstanding  ...  enc_paym_21  \
mean                 2.399848               3.012951  ...     2.313242   
std                  1.376391               0.683844  ...     1.247674   
min                  0.000000               1.000000  ...     0.000000   
25%                  2.000000               3.000000  ...     3.000000   
50%                  2.000000               3.000000  ...     3.000000   
75%                  2.000000               3.000000  ...     3.000000   
max                  6.000000               5.000000  ...     3.000000   

      enc_paym_22  enc_paym_23  enc_paym_24  enc_loans_account_holder_type  \
mean     2.343014     2.376717     3.576724                       1.027562   
std      1.228473     1.205555     1.035586                       0.276702   
min      0.000000     0.000000     1.000000                       0.000000   
25%      3.000000     3.000000     4.000000                       1.000000   
50%      3.000000     3.000000     4.000000                       1.000000   
75%      3.000000     3.000000     4.000000                       1.000000   
max      3.000000     3.000000     4.000000                       6.000000   

      enc_loans_credit_status  enc_loans_credit_type  enc_loans_account_cur  \
mean                 2.694898               3.353936               1.002386   
std                  0.489136               1.057304               0.059093   
min                  0.000000               0.000000               0.000000   
25%                  2.000000               3.000000               1.000000   
50%                  3.000000               4.000000               1.000000   
75%                  3.000000               4.000000               1.000000   
max                  6.000000               5.000000               3.000000   

      pclose_flag  fclose_flag  
mean     0.172138     0.223934  
std      0.377501     0.416878  
min      0.000000     0.000000  
25%      0.000000     0.000000  
50%      0.000000     0.000000  
75%      0.000000     0.000000  
max      1.000000     1.000000  

[7 rows x 60 columns]

In [4]:
round(db.describe().iloc[1, 1] + db.describe().iloc[2, 1] * 3)

22

In [58]:
arr = db.values[0].astype(np.int8)
arr

array([ 0,  1, 18,  9,  2,  3, 16, 10, 11,  3,  3,  0,  2, 11,  6, 16,  5,
        4,  8,  1,  1,  1,  1,  1, 16,  2, 17,  1,  1,  1,  0,  0,  3,  3,
        3,  3,  3,  3,  3,  3,  3,  4,  3,  3,  3,  3,  3,  3,  3,  3,  4,
        3,  3,  3,  4,  1,  3,  4,  1,  0,  0], dtype=int8)

In [59]:
obj = arr.tobytes()

In [60]:
obj

b'\x00\x01\x12\t\x02\x03\x10\n\x0b\x03\x03\x00\x02\x0b\x06\x10\x05\x04\x08\x01\x01\x01\x01\x01\x10\x02\x11\x01\x01\x01\x00\x00\x03\x03\x03\x03\x03\x03\x03\x03\x03\x04\x03\x03\x03\x03\x03\x03\x03\x03\x04\x03\x03\x03\x04\x01\x03\x04\x01\x00\x00'

In [63]:
np.frombuffer(obj, dtype='int8')

array([ 0,  1, 18,  9,  2,  3, 16, 10, 11,  3,  3,  0,  2, 11,  6, 16,  5,
        4,  8,  1,  1,  1,  1,  1, 16,  2, 17,  1,  1,  1,  0,  0,  3,  3,
        3,  3,  3,  3,  3,  3,  3,  4,  3,  3,  3,  3,  3,  3,  3,  3,  4,
        3,  3,  3,  4,  1,  3,  4,  1,  0,  0], dtype=int8)

In [56]:
def transform_dataframe(df):
    d = dict()
    values = df.values

    for value in values:
        try:
            d[value[0]].append(value[1:].astype(np.int8))
        except:
            d[value[0]] = list()
            d[value[0]].append(value[1:].astype(np.int8))
            
    return d

In [49]:
len(arr)

250000

In [61]:
def make_client_history(clients, num_rn, num_columns):
    row = np.zeros((num_rn, num_columns), dtype=np.int8)
    length = len(clients) 

    for i in range(0, min(num_rn,length)):
        row[num_rn-1-i] = clients[length-1-i][1:]
    
    return row

In [41]:
make_row(arr[0])

array([[ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       ...,
       [ 2,  9,  2, ...,  1,  0,  0],
       [ 1,  9, 11, ...,  1,  0,  0],
       [ 7,  9,  2, ...,  1,  0,  0]], dtype=int8)

In [26]:
values = list()

In [53]:
for i in tqdm(range(len(arr))):
    values.append(make_client_history(arr[i], 25, 59))

  0%|          | 0/250000 [00:00<?, ?it/s]

In [65]:
def transfrom_data(df, num_rn, num_columns):
    clients = transform_dataframe(df)
    values = list()
    
    for i in range(len(clients)):
        values.append(make_client_history(clients[i], num_rn, num_columns))
    
    return values

In [66]:
transfrom_data(db, 25, 59)

[array([[ 0,  0,  0, ...,  0,  0,  0],
        [ 0,  0,  0, ...,  0,  0,  0],
        [ 0,  0,  0, ...,  0,  0,  0],
        ...,
        [ 2,  9,  2, ...,  1,  0,  0],
        [ 1,  9, 11, ...,  1,  0,  0],
        [ 7,  9,  2, ...,  1,  0,  0]], dtype=int8),
 array([[ 0,  0,  0, ...,  0,  0,  0],
        [ 0,  0,  0, ...,  0,  0,  0],
        [ 0,  0,  0, ...,  0,  0,  0],
        ...,
        [ 2,  5, 15, ...,  1,  0,  0],
        [ 7,  9,  4, ...,  1,  1,  1],
        [12,  6,  1, ...,  1,  0,  1]], dtype=int8),
 array([[ 0,  0,  0, ...,  0,  0,  0],
        [ 0,  0,  0, ...,  0,  0,  0],
        [ 0,  0,  0, ...,  0,  0,  0],
        ...,
        [ 0,  9,  4, ...,  1,  1,  1],
        [13, 14, 13, ...,  1,  0,  0],
        [12,  9,  4, ...,  1,  1,  1]], dtype=int8),
 array([[ 0,  0,  0, ...,  0,  0,  0],
        [ 0,  0,  0, ...,  0,  0,  0],
        [ 0,  0,  0, ...,  0,  0,  0],
        ...,
        [ 2,  9,  4, ...,  1,  1,  1],
        [ 1,  1,  8, ...,  1,  0,  0],
        [

limit_output extension: Maximum message size of 10000 exceeded with 258845 characters